### ISSUE TITLE
@libp2p/transport-tcp failing build with p-events@7.0.2

### ISSUE THREAD

**Issue by tabcat** [libp2p/js-libp2p#3368]
- **Version**:

main branch

- **Subsystem**:

@libp2p/tcp

#### Severity:

Failing build

#### Description:

```bash
> @libp2p/tcp@11.0.9 build
> aegir build

[18:33:25] tsc [started]
src/listener.ts(272,19): error TS2345: Argument of type 'CancelablePromise<unknown>' is not assignable to parameter of type 'Promise<void>'.
  Types of property 'then' are incompatible.
    Type '<TResult1 = unknown, TResult2 = never>(onfulfilled?: ((value: unknown) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | null | undefined) => Promise<...>' is not assignable to type '<TResult1 = void, TResult2 = never>(onfulfilled?: ((value: void) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<...>) | null | undefined) => Promise<...>'.
      Types of parameters 'onfulfilled' and 'onfulfilled' are incompatible.
        Types of parameters 'value' and 'value' are incompatible.
          Type 'unknown' is not assignable to type 'void'.
src/listener.ts(285,21): error TS2345: Argument of type 'CancelablePromise<unknown>' is not assignable to parameter of type 'Promise<void>'.
  Types of property 'then' are incompatible.
    Type '<TResult1 = unknown, TResult2 = never>(onfulfilled?: ((value: unknown) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | null | undefined) => Promise<...>' is not assignable to type '<TResult1 = void, TResult2 = never>(onfulfilled?: ((value: void) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<...>) | null | undefined) => Promise<...>'.
      Types of parameters 'onfulfilled' and 'onfulfilled' are incompatible.
        Types of parameters 'value' and 'value' are incompatible.
          Type 'unknown' is not assignable to type 'void'.
[18:33:27] tsc [failed]
[18:33:27] → Command failed with exit code 1: tsc
```

Affected lines:

https://github.com/libp2p/js-libp2p/blob/851395edf7a5ffdef39a90ca5417a5db0da30520/packages/transport-tcp/src/listener.ts#L269-L285

Previous type 
```ts
pEvent<"timeout", any>(emitter: Emitter<"timeout", [any]>, event: string | symbol | ReadonlyArray<string | symbol>, options?: Options<any> | undefined): CancelablePromise<any>
```

7.0.2 type

```ts
pEvent<Record<string | symbol, unknown[]>, "close">(emitter: TypedEventEmitter<Record<string | symbol, unknown[]>>, event: "close", options?: Options<unknown> | undefined): CancelablePromise<unknown>
```

#### Steps to reproduce the error:

clean install and build

**Comment by tabcat** [comment]
Closed by https://github.com/libp2p/js-libp2p/pull/3369
