### ISSUE TITLE
Typescript build error

### ISSUE THREAD

**Issue by tuyennhv** [libp2p/js-libp2p#1088]
This is a continuation of #1073

- **Version**:
0.35.6

- **Platform**:
Mac OS X

- **Subsystem**:

#### Severity:
High - Lodestar could not compile

#### Description:
Compilation error when using v0.35.6 with lodestar:

```
@chainsafe/lodestar: ../../node_modules/libp2p/node_modules/native-abort-controller/dist/src/index.d.ts:1:10 - error TS2661: Cannot export 'AbortSignal'. Only local declarations can be exported from a module.
@chainsafe/lodestar: 1 export { AbortSignal, AbortController };
@chainsafe/lodestar:            ~~~~~~~~~~~
@chainsafe/lodestar: ../../node_modules/libp2p/node_modules/native-abort-controller/dist/src/index.d.ts:1:23 - error TS2661: Cannot export 'AbortController'. Only local declarations can be exported from a module.
@chainsafe/lodestar: 1 export { AbortSignal, AbortController };
```

#### Steps to reproduce the error:
Build 0.35.6 with lodestar

**Comment by tuyennhv** [comment]
PR in progress https://github.com/achingbrain/native-abort-controller/pull/5

**Comment by tuyennhv** [comment]
there's a work in progress to remove `abort-controller` dependencies https://github.com/ipfs/js-ipfs/issues/4001, need to confirm again after that's done

**Comment by wemeetagain** [comment]
may be worth re-checking now

**Comment by tuyennhv** [comment]
@wemeetagain  latest master works with version 3.0.0 of timeout-abort-controller, I'm working on fixing types in lodestar.

@achingbrain waiting for a new release of js-libp2p to close this issue

**Comment by tuyennhv** [comment]
issue is fixed on master, closing
