### ISSUE TITLE
`Peer` type not defined in`peer-store` since 0.34.0

### ISSUE THREAD

**Issue by D4nte** [libp2p/js-libp2p#1105]
- **Version**: 0.34.0 to 0.35.8
- **Platform**: `Linux 5.10.84-1-MANJARO #1 SMP PREEMPT Wed Dec 8 09:50:30 UTC 2021 x86_64 GNU/Linux`

- **Subsystem**: peer-store
- 
#### Severity: High
API breakage

#### Description:
Using TypeScript,  use the `Peer` type defined in `peer-store/index.js`. Working fine with 0.33.0.
Said `Peer` type is not present in peer-store/index.d.ts since 0.34.0 and onward.

#### Steps to reproduce the error:

Use `Peer` from `peer-store` with `libp2p@0.33.0`:

```ts
import { Peer } from 'libp2p/dist/src/peer-store';
```

It works.

Upgrade to any newer version of `libp2p`, you will get a missing type error:

```
src/lib/select_peer.ts:2:10 - error TS2305: Module '"libp2p/src/peer-store"' has no exported member 'Peer'.

2 import { Peer } from 'libp2p/src/peer-store';
```

### Notes

In 0.34.0, `aegir` was bumped (https://github.com/libp2p/js-libp2p/commit/3bed7b4cb25157191b29d4b058cb6222eb3bfcd7) from `33.1.1` to `36.0.0`. I am guessing this is the origin of the issue. Currently investigating.

**Comment by D4nte** [comment]
Now resolved
